package sk.listok.zssk.zssklistok;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.SearchView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;



public class TrainSearchFragment extends Fragment {

    private View rootView;
    private ArrayList<TrainStation> stations;

    private ListView lv;
    private SearchView sv;

    String statios1[] = {"Ba","KE","ZV","ZA"};
    ArrayAdapter<String> adapter;
    ListAdapter ad;

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        rootView = inflater.inflate(R.layout.fragment_train_search, container, false);
        //populatestationsList();

        lv = (ListView) rootView.findViewById(R.id.listViewTrain);
        sv = (SearchView) rootView.findViewById(R.id.searchViewTrain);
        adapter = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,getItems());

        lv.setAdapter(adapter);
        sv.clearFocus();// requestFocus(); // hodim focus na vyhladavanie

        sv.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {

                return true;
            }



            @Override
            public boolean onQueryTextChange(String newText) {

                //adapter.clear()

                adapter.getFilter().filter(newText);
              //  ArrayList<String> filtered = new ArrayList<String>();
              //  filtered.add(adapter.getItem(0));
              //  adapter = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,filtered);
              //  lv.setAdapter(adapter);
                return true;
            }
        });

        return rootView;
    }


    public void clearFilter(){
        sv.setQuery("",false);
        adapter.getFilter().filter("");
    }


    private String[] getItems(){
        populatestationsList();
        String ret[] = new String[stations.size()];
        int i =0;
        for(TrainStation tr : stations){
            ret[i++] = tr.getName();
        }

        return ret;
    }

    private void populatestationsList() {
        stations = new ArrayList<TrainStation>();
        stations.add(new TrainStation("Zvolen"));
        stations.add(new TrainStation("Žilina"));
        stations.add(new TrainStation("Košice"));
        stations.add(new TrainStation("Bratislava hl.st."));
        stations.add(new TrainStation("Trenčín"));
        stations.add(new TrainStation("Turčianske Teplice"));
        stations.add(new TrainStation("Banská Bystrica"));
        loadAll();
    }

    private void loadAll(){
        stations.add(new TrainStation("Abovce"));
        stations.add(new TrainStation("Alekšince"));
        stations.add(new TrainStation("Andač"));
        stations.add(new TrainStation("Babiná"));
        stations.add(new TrainStation("Bacúch"));
        stations.add(new TrainStation("Báhoň"));
        stations.add(new TrainStation("Bajč"));
        stations.add(new TrainStation("Balvany"));
        stations.add(new TrainStation("Bánov"));
        stations.add(new TrainStation("Bánovce nad Bebravou"));
        stations.add(new TrainStation("Bánovce nad Ondavou"));
        stations.add(new TrainStation("Bánréve MÁV"));
        stations.add(new TrainStation("Banská Belá"));
        stations.add(new TrainStation("Banská Belá zastávka"));
        stations.add(new TrainStation("Banská Bystrica"));
        stations.add(new TrainStation("Banská Bystrica mesto"));
        stations.add(new TrainStation("Banská Štiavnica"));
        stations.add(new TrainStation("Banský Studenec"));
        stations.add(new TrainStation("Barca"));
        stations.add(new TrainStation("Bardejov"));
        stations.add(new TrainStation("Bartošova Lehôtka"));
        stations.add(new TrainStation("Bartošovce"));
        stations.add(new TrainStation("Behynce"));
        stations.add(new TrainStation("Belá nad Cirochou"));
        stations.add(new TrainStation("Belina"));
        stations.add(new TrainStation("Beluša"));
        stations.add(new TrainStation("Beňuš"));
        stations.add(new TrainStation("Bernolákovo"));
        stations.add(new TrainStation("Beša"));
        stations.add(new TrainStation("Betliar"));
        stations.add(new TrainStation("Biel"));
        stations.add(new TrainStation("Bielovce"));
        stations.add(new TrainStation("Bíňa"));
        stations.add(new TrainStation("Bíňa zastávka"));
        stations.add(new TrainStation("Bíňovce"));
        stations.add(new TrainStation("Biskupová"));
        stations.add(new TrainStation("Blhovce"));
        stations.add(new TrainStation("Bodza"));
        stations.add(new TrainStation("Bohdanovce"));
        stations.add(new TrainStation("Bohúňovo"));
        stations.add(new TrainStation("Boleráz"));
        stations.add(new TrainStation("Bolešov"));
        stations.add(new TrainStation("Borčice"));
        stations.add(new TrainStation("Borský Mikuláš"));
        stations.add(new TrainStation("Borša"));
        stations.add(new TrainStation("Bošany"));
        stations.add(new TrainStation("Branč"));
        stations.add(new TrainStation("Bratislava hlavná stanica"));
        stations.add(new TrainStation("Bratislava predmestie"));
        stations.add(new TrainStation("Bratislava ústredná nákladná stanica"));
        stations.add(new TrainStation("Bratislava východ"));
        stations.add(new TrainStation("Bratislava-Lamač"));
        stations.add(new TrainStation("Bratislava-Nové Mesto"));
        stations.add(new TrainStation("Bratislava-Petržalka"));
        stations.add(new TrainStation("Bratislava-Rača"));
        stations.add(new TrainStation("Bratislava-Vajnory"));
        stations.add(new TrainStation("Bratislava-Vinohrady"));
        stations.add(new TrainStation("Bratislava-Železná studienka"));
        stations.add(new TrainStation("Břeclav ČD"));
        stations.add(new TrainStation("Brekov"));
        stations.add(new TrainStation("Brestovany"));
        stations.add(new TrainStation("Brestovec"));
        stations.add(new TrainStation("Breznička"));
        stations.add(new TrainStation("Brezno"));
        stations.add(new TrainStation("Brezno mesto"));
        stations.add(new TrainStation("Brezno-Halny"));
        stations.add(new TrainStation("Brezno-Rohozná"));
        stations.add(new TrainStation("Brezová pod Bradlom"));
        stations.add(new TrainStation("Brezová pod Bradlom zastávka"));
        stations.add(new TrainStation("Brodno"));
        stations.add(new TrainStation("Brodské"));
        stations.add(new TrainStation("Brunovce"));
        stations.add(new TrainStation("Brusno kúpele"));
        stations.add(new TrainStation("Budča"));
        stations.add(new TrainStation("Budkovce"));
        stations.add(new TrainStation("Bujakovo"));
        stations.add(new TrainStation("Buková"));
        stations.add(new TrainStation("Bušovce"));
        stations.add(new TrainStation("Bystrany na Spiši"));
        stations.add(new TrainStation("Bystré"));
        stations.add(new TrainStation("Bystričany"));
        stations.add(new TrainStation("Bytča"));
        stations.add(new TrainStation("Bytčica"));
        stations.add(new TrainStation("Bzenica"));
        stations.add(new TrainStation("Bziny"));
        stations.add(new TrainStation("Bzovík"));
        stations.add(new TrainStation("Bzovská Lehôtka"));
        stations.add(new TrainStation("Cerová-Lieskové"));
        stations.add(new TrainStation("Cestice"));
        stations.add(new TrainStation("Cífer"));
        stations.add(new TrainStation("Cinobaňa"));
        stations.add(new TrainStation("Čab-Sila"));
        stations.add(new TrainStation("Čab-Sila zastávka"));
        stations.add(new TrainStation("Čadca"));
        stations.add(new TrainStation("Čadca mesto"));
        stations.add(new TrainStation("Čadca zastávka"));
        stations.add(new TrainStation("Čachtice"));
        stations.add(new TrainStation("Čakajovce"));
        stations.add(new TrainStation("Čalovec"));
        stations.add(new TrainStation("Čamovce"));
        stations.add(new TrainStation("Čaňa"));
        stations.add(new TrainStation("Čata"));
        stations.add(new TrainStation("Čečejovce"));
        stations.add(new TrainStation("Čeľovce"));
        stations.add(new TrainStation("Čerenčany"));
        stations.add(new TrainStation("Čerhov"));
        stations.add(new TrainStation("Červená Skala"));
        stations.add(new TrainStation("Červenica"));
        stations.add(new TrainStation("České Brezovo"));
        stations.add(new TrainStation("Čierna nad Tisou"));
        stations.add(new TrainStation("Čierna nad Tisou zastávka"));
        stations.add(new TrainStation("Čierne nad Topľou"));
        stations.add(new TrainStation("Čierne pri Čadci"));
        stations.add(new TrainStation("Čierne pri Čadci zastávka"));
        stations.add(new TrainStation("Čierne-Polesie"));
        stations.add(new TrainStation("Čirč"));
        stations.add(new TrainStation("Číž kúpele"));
        stations.add(new TrainStation("Čoltovo"));
        stations.add(new TrainStation("Čremošné"));
        stations.add(new TrainStation("Danielov Dom"));
        stations.add(new TrainStation("Debraď"));
        stations.add(new TrainStation("Dedinky"));
        stations.add(new TrainStation("Demjata"));
        stations.add(new TrainStation("Demjata obec"));
        stations.add(new TrainStation("Detva"));
        stations.add(new TrainStation("Devičie"));
        stations.add(new TrainStation("Devínska Nová Ves"));
        stations.add(new TrainStation("Devínske Jazero"));
        stations.add(new TrainStation("Diakovce"));
        stations.add(new TrainStation("Diviaky"));
        stations.add(new TrainStation("Dlhá nad Oravou"));
        stations.add(new TrainStation("Dlhé nad Cirochou"));
        stations.add(new TrainStation("Dlhé nad Cirochou obec"));
        stations.add(new TrainStation("Dobrá"));
        stations.add(new TrainStation("Dobrá Niva"));
        stations.add(new TrainStation("Dobrá Niva zastávka"));
        stations.add(new TrainStation("Dobšiná"));
        stations.add(new TrainStation("Dobšinská Ľadová Jaskyňa"));
        stations.add(new TrainStation("Dohňany"));
        stations.add(new TrainStation("Dolná Seč"));
        stations.add(new TrainStation("Dolné Hámre"));
        stations.add(new TrainStation("Dolné Kočkovce"));
        stations.add(new TrainStation("Dolné Krškany"));
        stations.add(new TrainStation("Dolné Naštice"));
        stations.add(new TrainStation("Dolné Zahorany"));
        stations.add(new TrainStation("Dolný Bar"));
        stations.add(new TrainStation("Dolný Harmanec"));
        stations.add(new TrainStation("Dolný Hričov"));
        stations.add(new TrainStation("Dolný Kubín"));
        stations.add(new TrainStation("Dolný Kubín zastávka"));
        stations.add(new TrainStation("Dolný Smokovec"));
        stations.add(new TrainStation("Dolný Štál"));
        stations.add(new TrainStation("Domaníky"));
        stations.add(new TrainStation("Drahňov"));
        stations.add(new TrainStation("Drahovce zastávka"));
        stations.add(new TrainStation("Dražovce"));
        stations.add(new TrainStation("Drieňovec"));
        stations.add(new TrainStation("Drienovská Nová Ves"));
        stations.add(new TrainStation("Drienovská Nová Ves obec"));
        stations.add(new TrainStation("Dubnica nad Váhom"));
        stations.add(new TrainStation("Dubová"));
        stations.add(new TrainStation("Dubovec"));
        stations.add(new TrainStation("Dúbravka"));
        stations.add(new TrainStation("Dudince"));
        stations.add(new TrainStation("Dulov"));
        stations.add(new TrainStation("Dunajov"));
        stations.add(new TrainStation("Dunajská Streda"));
        stations.add(new TrainStation("Ďurková"));
        stations.add(new TrainStation("Dvorianky"));
        stations.add(new TrainStation("Dvorníky"));
        stations.add(new TrainStation("Dvorníky-Zádiel"));
        stations.add(new TrainStation("Dvory nad Žitavou"));
        stations.add(new TrainStation("Dyčka"));
        stations.add(new TrainStation("Fiľakovo"));
        stations.add(new TrainStation("Fiľakovo zastávka"));
        stations.add(new TrainStation("Forbasy"));
        stations.add(new TrainStation("Fulianka"));
        stations.add(new TrainStation("Galanta"));
        stations.add(new TrainStation("Gáň"));
        stations.add(new TrainStation("Gánovce"));
        stations.add(new TrainStation("Gašparovo"));
        stations.add(new TrainStation("Gbelce"));
        stations.add(new TrainStation("Gbely"));
        stations.add(new TrainStation("Gbely zastávka"));
        stations.add(new TrainStation("Geča"));
        stations.add(new TrainStation("Gelnica"));
        stations.add(new TrainStation("Gelnica mesto"));
        stations.add(new TrainStation("Gelnica zastávka"));
        stations.add(new TrainStation("Gemer"));
        stations.add(new TrainStation("Gemerská Hôrka"));
        stations.add(new TrainStation("Gemerská Hôrka zastávka"));
        stations.add(new TrainStation("Gemerská Panica"));
        stations.add(new TrainStation("Gemerská Poloma"));
        stations.add(new TrainStation("Gemerský Milhosť"));
        stations.add(new TrainStation("Gočovo"));
        stations.add(new TrainStation("Gortva"));
        stations.add(new TrainStation("Gyňov"));
        stations.add(new TrainStation("Hačava"));
        stations.add(new TrainStation("Hačava skálie"));
        stations.add(new TrainStation("Hadovce"));
        stations.add(new TrainStation("Hajnáčka"));
        stations.add(new TrainStation("Handlová"));
        stations.add(new TrainStation("Haniska pri Košiciach"));
        stations.add(new TrainStation("Haniska pri Prešove"));
        stations.add(new TrainStation("Hankovce"));
        stations.add(new TrainStation("Hanušovce nad Topľou"));
        stations.add(new TrainStation("Hanušovce nad Topľou mesto"));
        stations.add(new TrainStation("Harichovce"));
        stations.add(new TrainStation("Harmanec"));
        stations.add(new TrainStation("Harmanec jaskyňa"));
        stations.add(new TrainStation("Hatalov"));
        stations.add(new TrainStation("Hažín nad Cirochov"));
        stations.add(new TrainStation("Helcmanovce"));
        stations.add(new TrainStation("Heľpa"));
        stations.add(new TrainStation("Henckovce"));
        stations.add(new TrainStation("Hencovce"));
        stations.add(new TrainStation("Hertník"));
        stations.add(new TrainStation("Hidasnémeti MÁV"));
        stations.add(new TrainStation("Hlboké"));
        stations.add(new TrainStation("Hliník nad Hronom"));
        stations.add(new TrainStation("Hlinné"));
        stations.add(new TrainStation("Hlohovec"));
        stations.add(new TrainStation("Hnilec"));
        stations.add(new TrainStation("Hnúšťa"));
        stations.add(new TrainStation("Hnúšťa zastávka"));
        stations.add(new TrainStation("Hodejov"));
        stations.add(new TrainStation("Hodonín ČD"));
        stations.add(new TrainStation("Hodonín zastávka ČD"));
        stations.add(new TrainStation("Holíč nad Moravou"));
        stations.add(new TrainStation("Holiša"));
        stations.add(new TrainStation("Hontianske Nemce"));
        stations.add(new TrainStation("Hontianske Tesáre"));
        stations.add(new TrainStation("Horná Lehota"));
        stations.add(new TrainStation("Horná Streda"));
        stations.add(new TrainStation("Horná Štubňa"));
        stations.add(new TrainStation("Horná Štubňa obec"));
        stations.add(new TrainStation("Horná Štubňa zastávka"));
        stations.add(new TrainStation("Horná Zlatná"));
        stations.add(new TrainStation("Horné Ozorovce"));
        stations.add(new TrainStation("Horné Srnie"));
        stations.add(new TrainStation("Horní Lideč ČD"));
        stations.add(new TrainStation("Horný Hričov"));
        stations.add(new TrainStation("Horný Pial"));
        stations.add(new TrainStation("Horný Smokovec"));
        stations.add(new TrainStation("Horovce"));
        stations.add(new TrainStation("Hrabovec nad Laborcom"));
        stations.add(new TrainStation("Hradište pod Vrátnom"));
        stations.add(new TrainStation("Hrachovište"));
        stations.add(new TrainStation("Hrachovo"));
        stations.add(new TrainStation("Hrboltová"));
        stations.add(new TrainStation("Hrebienok"));
        stations.add(new TrainStation("Hrhov"));
        stations.add(new TrainStation("Hrinište"));
        stations.add(new TrainStation("Hrkovce"));
        stations.add(new TrainStation("Hrnčiarska Ves"));
        stations.add(new TrainStation("Hrnčiarske Zalužany"));
        stations.add(new TrainStation("Hromoš"));
        stations.add(new TrainStation("Hronovce"));
        stations.add(new TrainStation("Hronsek"));
        stations.add(new TrainStation("Hronská Dúbrava"));
        stations.add(new TrainStation("Hronské Kľačany"));
        stations.add(new TrainStation("Hronský Beňadik"));
        stations.add(new TrainStation("Hucín"));
        stations.add(new TrainStation("Hul"));
        stations.add(new TrainStation("Humenné"));
        stations.add(new TrainStation("Humenné mesto"));
        stations.add(new TrainStation("Huncovce"));
        stations.add(new TrainStation("Hurbanovo"));
        stations.add(new TrainStation("Husiná"));
        stations.add(new TrainStation("Hutníky"));
        stations.add(new TrainStation("Chmeľnica"));
        stations.add(new TrainStation("Chotín"));
        stations.add(new TrainStation("Chrabrany"));
        stations.add(new TrainStation("Chrasť nad Hornádom"));
        stations.add(new TrainStation("Chrenovec"));
        stations.add(new TrainStation("Chvatimech"));
        stations.add(new TrainStation("Chynorany"));
        stations.add(new TrainStation("Ilava"));
        stations.add(new TrainStation("Ipeľský Sokolec"));
        stations.add(new TrainStation("Istebné"));
        stations.add(new TrainStation("Ivanka pri Dunaji"));
        stations.add(new TrainStation("Ivanka pri Nitre"));
        stations.add(new TrainStation("Jablonica"));
        stations.add(new TrainStation("Jablonica obec"));
        stations.add(new TrainStation("Jablonov nad Turňou"));
        stations.add(new TrainStation("Jablonové"));
        stations.add(new TrainStation("Jaklovce"));
        stations.add(new TrainStation("Jalná"));
        stations.add(new TrainStation("Jalovec"));
        stations.add(new TrainStation("Jasov"));
        stations.add(new TrainStation("Jastrabá"));
        stations.add(new TrainStation("Jatov"));
        stations.add(new TrainStation("Jazernica"));
        stations.add(new TrainStation("Jelenec"));
        stations.add(new TrainStation("Jelšava"));
        stations.add(new TrainStation("Jelšava zastávka"));
        stations.add(new TrainStation("Jelšavská Teplica"));
        stations.add(new TrainStation("Jelšovce"));
        stations.add(new TrainStation("Jesenské"));
        stations.add(new TrainStation("Jesenské údolie"));
        stations.add(new TrainStation("Jesenské zastávka"));
        stations.add(new TrainStation("Jovice"));
        stations.add(new TrainStation("Kalinovo"));
        stations.add(new TrainStation("Kalná nad Hronom"));
        stations.add(new TrainStation("Kalonda"));
        stations.add(new TrainStation("Kalša"));
        stations.add(new TrainStation("Kamanová"));
        stations.add(new TrainStation("Kamenica nad Cirochou"));
        stations.add(new TrainStation("Kamenica nad Cirochou dvor"));
        stations.add(new TrainStation("Kamenica nad Torysou"));
        stations.add(new TrainStation("Kameničná"));
        stations.add(new TrainStation("Kamenín"));
        stations.add(new TrainStation("Kamenný Most nad Hronom"));
        stations.add(new TrainStation("Kapince"));
        stations.add(new TrainStation("Kapušany pri Prešove"));
        stations.add(new TrainStation("Katarínska Huta"));
        stations.add(new TrainStation("Kátov"));
        stations.add(new TrainStation("Katúň"));
        stations.add(new TrainStation("Kechnec"));
        stations.add(new TrainStation("Kendice"));
        stations.add(new TrainStation("Kežmarok"));
        stations.add(new TrainStation("Kežmarok zastávka"));
        stations.add(new TrainStation("Kittsee ÖBB"));
        stations.add(new TrainStation("Kľačany"));
        stations.add(new TrainStation("Kľače"));
        stations.add(new TrainStation("Kláštor pod Znievom"));
        stations.add(new TrainStation("Klčovany"));
        stations.add(new TrainStation("Kluknava"));
        stations.add(new TrainStation("Kľušov"));
        stations.add(new TrainStation("Kmeťovo"));
        stations.add(new TrainStation("Kociha"));
        stations.add(new TrainStation("Kochanovce"));
        stations.add(new TrainStation("Kokava nad Rimavicou"));
        stations.add(new TrainStation("Kokava nad Rimavicou Liešnica"));
        stations.add(new TrainStation("Kolárovo"));
        stations.add(new TrainStation("Komárany"));
        stations.add(new TrainStation("Komárno"));
        stations.add(new TrainStation("Komárno škola"));
        stations.add(new TrainStation("Komárno závody"));
        stations.add(new TrainStation("Komárom MÁV"));
        stations.add(new TrainStation("Komárovce"));
        stations.add(new TrainStation("Komjatice"));
        stations.add(new TrainStation("Koniarovce"));
        stations.add(new TrainStation("Konská pri Rajci"));
        stations.add(new TrainStation("Kopčany"));
        stations.add(new TrainStation("Kostiviarska"));
        stations.add(new TrainStation("Kostoľany nad Hornádom"));
        stations.add(new TrainStation("Kostolná-Záriečie"));
        stations.add(new TrainStation("Koš"));
        stations.add(new TrainStation("Košeca"));
        stations.add(new TrainStation("Košice"));
        stations.add(new TrainStation("Košice predmestie"));
        stations.add(new TrainStation("Koškovce"));
        stations.add(new TrainStation("Košťany nad Turcom"));
        stations.add(new TrainStation("Kotešová"));
        stations.add(new TrainStation("Kozárovce"));
        stations.add(new TrainStation("Kozárovce zastávka"));
        stations.add(new TrainStation("Kozelník"));
        stations.add(new TrainStation("Kráľka"));
        stations.add(new TrainStation("Kráľová Lehota"));
        stations.add(new TrainStation("Kraľovany"));
        stations.add(new TrainStation("Kraľovany zastávka"));
        stations.add(new TrainStation("Krásna Hôrka"));
        stations.add(new TrainStation("Krásna nad Hornádom"));
        stations.add(new TrainStation("Krásno nad Kysucou"));
        stations.add(new TrainStation("Krásny Brod"));
        stations.add(new TrainStation("Kremnica"));
        stations.add(new TrainStation("Kremnické Bane"));
        stations.add(new TrainStation("Krišovská Liesková"));
        stations.add(new TrainStation("Krivá"));
        stations.add(new TrainStation("Kriváň"));
        stations.add(new TrainStation("Krivany"));
        stations.add(new TrainStation("Križovany nad Dudváhom"));
        stations.add(new TrainStation("Krompachy"));
        stations.add(new TrainStation("Krpeľany"));
        stations.add(new TrainStation("Krupina"));
        stations.add(new TrainStation("Krupina predmestie"));
        stations.add(new TrainStation("Krušovce"));
        stations.add(new TrainStation("Kuchyňa"));
        stations.add(new TrainStation("Kuklov"));
        stations.add(new TrainStation("Kunova Teplica"));
        stations.add(new TrainStation("Kútniky"));
        stations.add(new TrainStation("Kúty"));
        stations.add(new TrainStation("Kuzmice"));
        stations.add(new TrainStation("Kvetoslavov"));
        stations.add(new TrainStation("Kvetoslavov zastávka"));
        stations.add(new TrainStation("Kysucké Nové Mesto"));
        stations.add(new TrainStation("Lábske Jazero zastávka"));
        stations.add(new TrainStation("Lada"));
        stations.add(new TrainStation("Ladce"));
        stations.add(new TrainStation("Ladice"));
        stations.add(new TrainStation("Lanžhot ČD"));
        stations.add(new TrainStation("Lastovce"));
        stations.add(new TrainStation("Laškovce"));
        stations.add(new TrainStation("Lednické Rovne"));
        stations.add(new TrainStation("Lehnice"));
        stations.add(new TrainStation("Lenartovce"));
        stations.add(new TrainStation("Leopoldov"));
        stations.add(new TrainStation("Leopoldov zastávka"));
        stations.add(new TrainStation("Letanovce"));
        stations.add(new TrainStation("Levice"));
        stations.add(new TrainStation("Levoča"));
        stations.add(new TrainStation("Levočské Lúky"));
        stations.add(new TrainStation("Ličartovce"));
        stations.add(new TrainStation("Lietavská Lúčka"));
        stations.add(new TrainStation("Likier"));
        stations.add(new TrainStation("Lipany"));
        stations.add(new TrainStation("Lipovník"));
        stations.add(new TrainStation("Liptovská Teplá"));
        stations.add(new TrainStation("Liptovské Vlachy"));
        stations.add(new TrainStation("Liptovský Hrádok"));
        stations.add(new TrainStation("Liptovský Mikuláš"));
        stations.add(new TrainStation("Lisková"));
        stations.add(new TrainStation("Lok"));
        stations.add(new TrainStation("Lopej"));
        stations.add(new TrainStation("Lovinobaňa"));
        stations.add(new TrainStation("Lovinobaňa zastávka"));
        stations.add(new TrainStation("Lozorno"));
        stations.add(new TrainStation("Lubeník"));
        stations.add(new TrainStation("Ľubietová"));
        stations.add(new TrainStation("Ľubiša"));
        stations.add(new TrainStation("Ľubochňa"));
        stations.add(new TrainStation("Ľubotín"));
        stations.add(new TrainStation("Lučatín"));
        stations.add(new TrainStation("Lučenec"));
        stations.add(new TrainStation("Lučivná"));
        stations.add(new TrainStation("Lúčnica nad Žitavou"));
        stations.add(new TrainStation("Ludanice"));
        stations.add(new TrainStation("Ľudovítov"));
        stations.add(new TrainStation("Lúky nad Makytou"));
        stations.add(new TrainStation("Lupkow PKP"));
        stations.add(new TrainStation("Lužianky"));
        stations.add(new TrainStation("Lysá pod Makytou"));
        stations.add(new TrainStation("Makov"));
        stations.add(new TrainStation("Malá Lodina"));
        stations.add(new TrainStation("Malá Maňa"));
        stations.add(new TrainStation("Malá Paka"));
        stations.add(new TrainStation("Malacky"));
        stations.add(new TrainStation("Malé Ripňany"));
        stations.add(new TrainStation("Malé Zálužie"));
        stations.add(new TrainStation("Malý Čepčín"));
        stations.add(new TrainStation("Maňa"));
        stations.add(new TrainStation("Maňa zastávka"));
        stations.add(new TrainStation("Margecany"));
        stations.add(new TrainStation("Margecany zastávka"));
        stations.add(new TrainStation("Marchegg ÖBB"));
        stations.add(new TrainStation("Markušovce"));
        stations.add(new TrainStation("Martin"));
        stations.add(new TrainStation("Martinová"));
        stations.add(new TrainStation("Maša"));
        stations.add(new TrainStation("Maštinec"));
        stations.add(new TrainStation("Matejovce nad Hornádom"));
        stations.add(new TrainStation("Matejovce pri Poprade"));
        stations.add(new TrainStation("Medzev"));
        stations.add(new TrainStation("Medzibrod"));
        stations.add(new TrainStation("Medzibrodie nad Oravou"));
        stations.add(new TrainStation("Medzilaborce"));
        stations.add(new TrainStation("Medzilaborce mesto"));
        stations.add(new TrainStation("Melčice"));
        stations.add(new TrainStation("Michal na Ostrove"));
        stations.add(new TrainStation("Michal nad Žitavou"));
        stations.add(new TrainStation("Michaľany"));
        stations.add(new TrainStation("Michalová"));
        stations.add(new TrainStation("Michalová zastávka"));
        stations.add(new TrainStation("Michalovce"));
        stations.add(new TrainStation("Michalovce zastávka"));
        stations.add(new TrainStation("Mikušovce"));
        stations.add(new TrainStation("Milhostov"));
        stations.add(new TrainStation("Milochov"));
        stations.add(new TrainStation("Miloslavov"));
        stations.add(new TrainStation("Mládzovo"));
        stations.add(new TrainStation("Mlynárce"));
        stations.add(new TrainStation("Mlynky"));
        stations.add(new TrainStation("Mlynky zastávka"));
        stations.add(new TrainStation("Mníchova Lehota"));
        stations.add(new TrainStation("Mníšek nad Hnilcom"));
        stations.add(new TrainStation("Modra nad Cirochou"));
        stations.add(new TrainStation("Mokrá Lúka"));
        stations.add(new TrainStation("Mokraď"));
        stations.add(new TrainStation("Mokrance"));
        stations.add(new TrainStation("Moldava nad Bodvou"));
        stations.add(new TrainStation("Moldava nad Bodvou mesto"));
        stations.add(new TrainStation("Monastyr"));
        stations.add(new TrainStation("Moravský Ján"));
        stations.add(new TrainStation("Mosty u Jablunkova ČD"));
        stations.add(new TrainStation("Mosty u Jablunkova zastávka ČD"));
        stations.add(new TrainStation("Muráň"));
        stations.add(new TrainStation("Muránska Dlhá Lúka"));
        stations.add(new TrainStation("Muszyna PKP"));
        stations.add(new TrainStation("Mužla"));
        stations.add(new TrainStation("Myjava"));
        stations.add(new TrainStation("Mýtna"));
        stations.add(new TrainStation("Mýtna Nová Ves"));
        stations.add(new TrainStation("Nacina Ves"));
        stations.add(new TrainStation("Nadabula"));
        stations.add(new TrainStation("Nálepkovo"));
        stations.add(new TrainStation("Nálepkovo-Peklisko"));
        stations.add(new TrainStation("Neded"));
        stations.add(new TrainStation("Nedožery"));
        stations.add(new TrainStation("Nemcovce"));
        stations.add(new TrainStation("Nemecká"));
        stations.add(new TrainStation("Nemšová"));
        stations.add(new TrainStation("Nitra"));
        stations.add(new TrainStation("Nitra zastávka"));
        stations.add(new TrainStation("Nitrianske Pravno"));
        stations.add(new TrainStation("Nižná"));
        stations.add(new TrainStation("Nižná Myšľa"));
        stations.add(new TrainStation("Nižná Slaná"));
        stations.add(new TrainStation("Nižná Slaná obec"));
        stations.add(new TrainStation("Nižná Šebastová"));
        stations.add(new TrainStation("Nižné Ružbachy"));
        stations.add(new TrainStation("Nižný Hrabovec"));
        stations.add(new TrainStation("Nižný Kelčov"));
        stations.add(new TrainStation("Nižný Skalník"));
        stations.add(new TrainStation("Nosice"));
        stations.add(new TrainStation("Nová Baňa"));
        stations.add(new TrainStation("Nová Lesná"));
        stations.add(new TrainStation("Nová Maša"));
        stations.add(new TrainStation("Nová Polianka"));
        stations.add(new TrainStation("Nová Stráž"));
        stations.add(new TrainStation("Nová Ves nad Žitavou"));
        stations.add(new TrainStation("Nová Vieska"));
        stations.add(new TrainStation("Nováky"));
        stations.add(new TrainStation("Nové Košariská"));
        stations.add(new TrainStation("Nové Mesto nad Váhom"));
        stations.add(new TrainStation("Nové Sady"));
        stations.add(new TrainStation("Nové Zámky"));
        stations.add(new TrainStation("Nový Smokovec"));
        stations.add(new TrainStation("Nožné Čabiny"));
        stations.add(new TrainStation("Obišovce"));
        stations.add(new TrainStation("Ochodnica"));
        stations.add(new TrainStation("Ochtiná"));
        stations.add(new TrainStation("Okoč"));
        stations.add(new TrainStation("Okoličná na Ostrove"));
        stations.add(new TrainStation("Okoličné"));
        stations.add(new TrainStation("Olcnava"));
        stations.add(new TrainStation("Ondrochov"));
        stations.add(new TrainStation("Opatová nad Váhom"));
        stations.add(new TrainStation("Opatová pri Lučenci"));
        stations.add(new TrainStation("Orávka"));
        stations.add(new TrainStation("Oravský Podzámok"));
        stations.add(new TrainStation("Oravský Podzámok zastávka"));
        stations.add(new TrainStation("Orechová Potôň"));
        stations.add(new TrainStation("Orkucany"));
        stations.add(new TrainStation("Orlov"));
        stations.add(new TrainStation("Oslany"));
        stations.add(new TrainStation("Ostratice"));
        stations.add(new TrainStation("Osuské"));
        stations.add(new TrainStation("Oščadnica"));
        stations.add(new TrainStation("Oždany"));
        stations.add(new TrainStation("Palárikovo"));
        stations.add(new TrainStation("Paprad"));
        stations.add(new TrainStation("Parchovany"));
        stations.add(new TrainStation("Párnica"));
        stations.add(new TrainStation("Partizánske"));
        stations.add(new TrainStation("Partizánske zastávka"));
        stations.add(new TrainStation("Pastovce"));
        stations.add(new TrainStation("Pašková"));
        stations.add(new TrainStation("Pavlovce"));
        stations.add(new TrainStation("Pečovská Nová Ves"));
        stations.add(new TrainStation("Pekná Vyhliadka"));
        stations.add(new TrainStation("Pernek pri Zohore"));
        stations.add(new TrainStation("Petrovce nad Laborcom"));
        stations.add(new TrainStation("Pezinok"));
        stations.add(new TrainStation("Pezinok zastávka"));
        stations.add(new TrainStation("Piešťany"));
        stations.add(new TrainStation("Píla"));
        stations.add(new TrainStation("Plavecké Podhradie"));
        stations.add(new TrainStation("Plavecký Mikuláš"));
        stations.add(new TrainStation("Plavecký Štvrtok"));
        stations.add(new TrainStation("Plaveč"));
        stations.add(new TrainStation("Plavnica"));
        stations.add(new TrainStation("Plešivec"));
        stations.add(new TrainStation("Plevník-Drieňové"));
        stations.add(new TrainStation("Počkaj"));
        stations.add(new TrainStation("Pod lesom"));
        stations.add(new TrainStation("Podbiel"));
        stations.add(new TrainStation("Podbrezová"));
        stations.add(new TrainStation("Podhájska"));
        stations.add(new TrainStation("Podhorany pri Kežmarku"));
        stations.add(new TrainStation("Podhorany pri Lužiankach"));
        stations.add(new TrainStation("Podkriváň"));
        stations.add(new TrainStation("Podolínec"));
        stations.add(new TrainStation("Podrečany"));
        stations.add(new TrainStation("Podtureň"));
        stations.add(new TrainStation("Podunajské Biskupice"));
        stations.add(new TrainStation("Podvysoká"));
        stations.add(new TrainStation("Podzámčok"));
        stations.add(new TrainStation("Pohorelá"));
        stations.add(new TrainStation("Pohorelská Maša"));
        stations.add(new TrainStation("Pohronská Polhora"));
        stations.add(new TrainStation("Pohronský Ruskov"));
        stations.add(new TrainStation("Polomka"));
        stations.add(new TrainStation("Polomka-Hámor"));
        stations.add(new TrainStation("Poltár"));
        stations.add(new TrainStation("Poluvsie"));
        stations.add(new TrainStation("Poprad-Spišská Sobota"));
        stations.add(new TrainStation("Poprad-Tatry"));
        stations.add(new TrainStation("Popradské Pleso"));
        stations.add(new TrainStation("Poriadie"));
        stations.add(new TrainStation("Porúbka"));
        stations.add(new TrainStation("Považany"));
        stations.add(new TrainStation("Považská Bystrica"));
        stations.add(new TrainStation("Považská Teplá"));
        stations.add(new TrainStation("Pozba"));
        stations.add(new TrainStation("Prakovce"));
        stations.add(new TrainStation("Prakovce zastávka"));
        stations.add(new TrainStation("Pravenec"));
        stations.add(new TrainStation("Predajná"));
        stations.add(new TrainStation("Predmier"));
        stations.add(new TrainStation("Preseľany nad Nitrou zastávka"));
        stations.add(new TrainStation("Prešov"));
        stations.add(new TrainStation("Prešov mesto"));
        stations.add(new TrainStation("Pribeník"));
        stations.add(new TrainStation("Pribeta"));
        stations.add(new TrainStation("Príbovce"));
        stations.add(new TrainStation("Priekopa"));
        stations.add(new TrainStation("Prievidza"));
        stations.add(new TrainStation("Prša"));
        stations.add(new TrainStation("Pruské"));
        stations.add(new TrainStation("Psiare"));
        stations.add(new TrainStation("Pstruša"));
        stations.add(new TrainStation("Púchov"));
        stations.add(new TrainStation("Púchov zastávka"));
        stations.add(new TrainStation("Púchov závody"));
        stations.add(new TrainStation("Pusté Čemerné"));
        stations.add(new TrainStation("Pusté Pole"));
        stations.add(new TrainStation("Pusté Úľany"));
        stations.add(new TrainStation("Radava"));
        stations.add(new TrainStation("Radošina"));
        stations.add(new TrainStation("Radvaň"));
        stations.add(new TrainStation("Radvaň nad Laborcom"));
        stations.add(new TrainStation("Radzovce"));
        stations.add(new TrainStation("Rajec"));
        stations.add(new TrainStation("Rajecké Teplice"));
        stations.add(new TrainStation("Rajka MÁV"));
        stations.add(new TrainStation("Raková"));
        stations.add(new TrainStation("Raková-Zemanov"));
        stations.add(new TrainStation("Rakovec"));
        stations.add(new TrainStation("Rapovce"));
        stations.add(new TrainStation("Raslavice"));
        stations.add(new TrainStation("Ráztočno"));
        stations.add(new TrainStation("Reca"));
        stations.add(new TrainStation("Remäta"));
        stations.add(new TrainStation("Revúca"));
        stations.add(new TrainStation("Revúcka Lehota"));
        stations.add(new TrainStation("Riečka"));
        stations.add(new TrainStation("Richnava"));
        stations.add(new TrainStation("Rimavská Baňa"));
        stations.add(new TrainStation("Rimavská Píla"));
        stations.add(new TrainStation("Rimavská Seč"));
        stations.add(new TrainStation("Rimavská Sobota"));
        stations.add(new TrainStation("Rimavské Brezovo"));
        stations.add(new TrainStation("Rimavské Janovce"));
        stations.add(new TrainStation("Rimavské Janovce obec"));
        stations.add(new TrainStation("Rimavské Zalužany"));
        stations.add(new TrainStation("Rišňovce"));
        stations.add(new TrainStation("Rohožník"));
        stations.add(new TrainStation("Rochovce"));
        stations.add(new TrainStation("Rochovce"));
        stations.add(new TrainStation("Roštár"));
        stations.add(new TrainStation("Rovinka"));
        stations.add(new TrainStation("Rožkovany"));
        stations.add(new TrainStation("Rožňava"));
        stations.add(new TrainStation("Rožňava mesto"));
        stations.add(new TrainStation("Rožňava predmestie"));
        stations.add(new TrainStation("Rudina"));
        stations.add(new TrainStation("Rudno nad Hronom"));
        stations.add(new TrainStation("Ruskov"));
        stations.add(new TrainStation("Ruskovce"));
        stations.add(new TrainStation("Rusovce"));
        stations.add(new TrainStation("Ružín"));
        stations.add(new TrainStation("Ružomberok"));
        stations.add(new TrainStation("Ružomberok-Rybárpole"));
        stations.add(new TrainStation("Rybany"));
        stations.add(new TrainStation("Sabinov"));
        stations.add(new TrainStation("Sačurov"));
        stations.add(new TrainStation("Sása-Pliešovce"));
        stations.add(new TrainStation("Sátoraljaújhely MÁV"));
        stations.add(new TrainStation("Sečovce"));
        stations.add(new TrainStation("Sečovská Polianka"));
        stations.add(new TrainStation("Sedliacka Dubová"));
        stations.add(new TrainStation("Sedmerovec"));
        stations.add(new TrainStation("Sekule"));
        stations.add(new TrainStation("Seňa"));
        stations.add(new TrainStation("Senec"));
        stations.add(new TrainStation("Senica"));
        stations.add(new TrainStation("Sereď"));
        stations.add(new TrainStation("Sibír"));
        stations.add(new TrainStation("Siladice"));
        stations.add(new TrainStation("Skalica na Slovensku"));
        stations.add(new TrainStation("Skalité"));
        stations.add(new TrainStation("Skalité pod Poľanou"));
        stations.add(new TrainStation("Skalité zastávka"));
        stations.add(new TrainStation("Skalité-Kudlov"));
        stations.add(new TrainStation("Skalité-Serafínov"));
        stations.add(new TrainStation("Skalnaté Pleso"));
        stations.add(new TrainStation("Sklené pri Handlovej"));
        stations.add(new TrainStation("Sládkovičovo"));
        stations.add(new TrainStation("Slaná Lehota"));
        stations.add(new TrainStation("Slanec"));
        stations.add(new TrainStation("Slatina"));
        stations.add(new TrainStation("Slavec jaskyňa"));
        stations.add(new TrainStation("Slavošovce"));
        stations.add(new TrainStation("Slavošovce obec"));
        stations.add(new TrainStation("Sľažany"));
        stations.add(new TrainStation("Slepčany"));
        stations.add(new TrainStation("Sliač kúpele"));
        stations.add(new TrainStation("Slovenská Ľupča"));
        stations.add(new TrainStation("Slovenská Ľupča-Príboj"));
        stations.add(new TrainStation("Slovenské Nové Mesto"));
        stations.add(new TrainStation("Smižany"));
        stations.add(new TrainStation("Smolenice"));
        stations.add(new TrainStation("Snina"));
        stations.add(new TrainStation("Snina mesto"));
        stations.add(new TrainStation("Snina predmestie"));
        stations.add(new TrainStation("Soblahov"));
        stations.add(new TrainStation("Soľ"));
        stations.add(new TrainStation("Solinky"));
        stations.add(new TrainStation("Sološnica"));
        stations.add(new TrainStation("Somosköújfalu MÁV"));
        stations.add(new TrainStation("Somotor"));
        stations.add(new TrainStation("Spišská Belá zastávka"));
        stations.add(new TrainStation("Spišská Nová Ves"));
        stations.add(new TrainStation("Spišské Podhradie"));
        stations.add(new TrainStation("Spišské Tomášovce"));
        stations.add(new TrainStation("Spišské Vlachy"));
        stations.add(new TrainStation("Spišské Vlachy mesto"));
        stations.add(new TrainStation("Spišský Štiavnik"));
        stations.add(new TrainStation("Stakčín"));
        stations.add(new TrainStation("Stanča"));
        stations.add(new TrainStation("Stankovany"));
        stations.add(new TrainStation("Stará Kremnička"));
        stations.add(new TrainStation("Stará Lesná"));
        stations.add(new TrainStation("Stará Ľubovňa"));
        stations.add(new TrainStation("Stará Turá"));
        stations.add(new TrainStation("Stará Voda"));
        stations.add(new TrainStation("Starý Smokovec"));
        stations.add(new TrainStation("Starý Smokovec lanovka"));
        stations.add(new TrainStation("Staškov"));
        stations.add(new TrainStation("Staškov zastávka"));
        stations.add(new TrainStation("Stožok"));
        stations.add(new TrainStation("Stratená"));
        stations.add(new TrainStation("Strážky"));
        stations.add(new TrainStation("Strážky zastávka"));
        stations.add(new TrainStation("Strážske"));
        stations.add(new TrainStation("Strečno"));
        stations.add(new TrainStation("Streda nad Bodrogom"));
        stations.add(new TrainStation("Strekov"));
        stations.add(new TrainStation("Strelenka"));
        stations.add(new TrainStation("Střelná ČD"));
        stations.add(new TrainStation("Studený Potok"));
        stations.add(new TrainStation("Sučany"));
        stations.add(new TrainStation("Sudoměřice nad Moravou ČD"));
        stations.add(new TrainStation("Sukov"));
        stations.add(new TrainStation("Sušany"));
        stations.add(new TrainStation("Svätý Jur"));
        stations.add(new TrainStation("Svinná"));
        stations.add(new TrainStation("Svit"));
        stations.add(new TrainStation("Svrčinovec"));
        stations.add(new TrainStation("Svrčinovec zastávka"));
        stations.add(new TrainStation("Sykavka"));
        stations.add(new TrainStation("Šahy"));
        stations.add(new TrainStation("Šajdíkove Humence"));
        stations.add(new TrainStation("Šaľa"));
        stations.add(new TrainStation("Šalková"));
        stations.add(new TrainStation("Šarišské Lúky"));
        stations.add(new TrainStation("Šarišské Michaľany"));
        stations.add(new TrainStation("Šášovské Podhradie"));
        stations.add(new TrainStation("Šaštín-Stráže"));
        stations.add(new TrainStation("Šelpice"));
        stations.add(new TrainStation("Šenkvice"));
        stations.add(new TrainStation("Šiatorská Bukovinka"));
        stations.add(new TrainStation("Šiba"));
        stations.add(new TrainStation("Šíd"));
        stations.add(new TrainStation("Štítník"));
        stations.add(new TrainStation("Štítník mesto"));
        stations.add(new TrainStation("Štrba"));
        stations.add(new TrainStation("Štrba zastávka"));
        stations.add(new TrainStation("Štrbské Pleso"));
        stations.add(new TrainStation("Štrkovec"));
        stations.add(new TrainStation("Štúrovo"));
        stations.add(new TrainStation("Šurany"));
        stations.add(new TrainStation("Šurany zastávka"));
        stations.add(new TrainStation("Šúrovce"));
        stations.add(new TrainStation("Šútovo"));
        stations.add(new TrainStation("Švedlár"));
        stations.add(new TrainStation("Švedlár zastávka"));
        stations.add(new TrainStation("Švošov"));
        stations.add(new TrainStation("Ťahanovce"));
        stations.add(new TrainStation("Tatranská Lesná"));
        stations.add(new TrainStation("Tatranská Lomnica"));
        stations.add(new TrainStation("Tatranská Lomnica zastávka (Eurocamp));"));
        stations.add(new TrainStation("Tatranská Polianka"));
        stations.add(new TrainStation("Tatranské Zruby"));
        stations.add(new TrainStation("Tatranský Lieskovec"));
        stations.add(new TrainStation("Tekovská Breznica"));
        stations.add(new TrainStation("Tekovské Lužany"));
        stations.add(new TrainStation("Tekovský Hrádok"));
        stations.add(new TrainStation("Telgárt"));
        stations.add(new TrainStation("Telgárt penzión"));
        stations.add(new TrainStation("Teplička nad Hornádom"));
        stations.add(new TrainStation("Teplička nad Váhom"));
        stations.add(new TrainStation("Terany"));
        stations.add(new TrainStation("Tesárske Mlyňany"));
        stations.add(new TrainStation("Tešedíkovo"));
        stations.add(new TrainStation("Tisovec"));
        stations.add(new TrainStation("Tisovec mesto"));
        stations.add(new TrainStation("Tisovec-Bánovo"));
        stations.add(new TrainStation("Tlmače"));
        stations.add(new TrainStation("Tomášovce"));
        stations.add(new TrainStation("Topoľčany"));
        stations.add(new TrainStation("Topoľnica"));
        stations.add(new TrainStation("Toporec"));
        stations.add(new TrainStation("Tornaľa"));
        stations.add(new TrainStation("Trebejov"));
        stations.add(new TrainStation("Trebišov"));
        stations.add(new TrainStation("Trebišov zastávka"));
        stations.add(new TrainStation("Trenčianska Teplá"));
        stations.add(new TrainStation("Trenčianska Teplá obec"));
        stations.add(new TrainStation("Trenčianska Teplá zastávka"));
        stations.add(new TrainStation("Trenčianska Turná"));
        stations.add(new TrainStation("Trenčianske Bohuslavice"));
        stations.add(new TrainStation("Trenčianske Jastrabie"));
        stations.add(new TrainStation("Trenčianske Teplice"));
        stations.add(new TrainStation("Trenčianske Teplice sídlisko"));
        stations.add(new TrainStation("Trenčianske Teplice zastávka"));
        stations.add(new TrainStation("Trenčín"));
        stations.add(new TrainStation("Trenčín predmestie"));
        stations.add(new TrainStation("Tretí Hámor"));
        stations.add(new TrainStation("Trnava"));
        stations.add(new TrainStation("Trnavá Hora"));
        stations.add(new TrainStation("Trnava predmestie"));
        stations.add(new TrainStation("Trnovec nad Váhom"));
        stations.add(new TrainStation("Trstená"));
        stations.add(new TrainStation("Tulčík"));
        stations.add(new TrainStation("Tupá"));
        stations.add(new TrainStation("Turany"));
        stations.add(new TrainStation("Turček"));
        stations.add(new TrainStation("Turčianske Teplice"));
        stations.add(new TrainStation("Turňa nad Bodvou"));
        stations.add(new TrainStation("Turzovka"));
        stations.add(new TrainStation("Turzovka zastávka"));
        stations.add(new TrainStation("Tvrdošín"));
        stations.add(new TrainStation("Tvrdošovce"));
        stations.add(new TrainStation("Udavské"));
        stations.add(new TrainStation("Uľanka"));
        stations.add(new TrainStation("Úľany nad Žitavou"));
        stations.add(new TrainStation("Úpor"));
        stations.add(new TrainStation("Utekáč"));
        stations.add(new TrainStation("Vaďovce"));
        stations.add(new TrainStation("Valaliky"));
        stations.add(new TrainStation("Valaská"));
        stations.add(new TrainStation("Vaľkovňa"));
        stations.add(new TrainStation("Vaniškovce"));
        stations.add(new TrainStation("Varín"));
        stations.add(new TrainStation("Važec"));
        stations.add(new TrainStation("Včelínce"));
        stations.add(new TrainStation("Veľaty"));
        stations.add(new TrainStation("Veličná"));
        stations.add(new TrainStation("Veľká Ida"));
        stations.add(new TrainStation("Veľká Lodina"));
        stations.add(new TrainStation("Veľká Lomnica"));
        stations.add(new TrainStation("Veľká Lúka"));
        stations.add(new TrainStation("Veľká Paka"));
        stations.add(new TrainStation("Veľká Ves"));
        stations.add(new TrainStation("Veľké Bielice"));
        stations.add(new TrainStation("Veľké Blahovo"));
        stations.add(new TrainStation("Veľké Kapušany"));
        stations.add(new TrainStation("Veľké Kapušany zastávka"));
        stations.add(new TrainStation("Veľké Kostoľany"));
        stations.add(new TrainStation("Veľké Kozmálovce"));
        stations.add(new TrainStation("Veľké Leváre"));
        stations.add(new TrainStation("Veľké Ripňany"));
        stations.add(new TrainStation("Veľké Teriakovce"));
        stations.add(new TrainStation("Veľké Uherce"));
        stations.add(new TrainStation("Veľký Biel"));
        stations.add(new TrainStation("Veľký Horeš"));
        stations.add(new TrainStation("Veľký Kýr"));
        stations.add(new TrainStation("Veľký Meder"));
        stations.add(new TrainStation("Veľký Slavkov"));
        stations.add(new TrainStation("Veľký Šariš"));
        stations.add(new TrainStation("Vernár"));
        stations.add(new TrainStation("Vidová"));
        stations.add(new TrainStation("Vígľaš"));
        stations.add(new TrainStation("Violín"));
        stations.add(new TrainStation("Višňové"));
        stations.add(new TrainStation("Vítkovce"));
        stations.add(new TrainStation("Vlachovo"));
        stations.add(new TrainStation("Vlachovo obec"));
        stations.add(new TrainStation("Vlársky průsmyk ČD"));
        stations.add(new TrainStation("Vlčany"));
        stations.add(new TrainStation("Vlkanová"));
        stations.add(new TrainStation("Vojany"));
        stations.add(new TrainStation("Vojčice"));
        stations.add(new TrainStation("Volica"));
        stations.add(new TrainStation("Volkovce"));
        stations.add(new TrainStation("Voznica"));
        stations.add(new TrainStation("Vráble"));
        stations.add(new TrainStation("Vranov nad Topľou"));
        stations.add(new TrainStation("Vranov nad Topľou predmestie"));
        stations.add(new TrainStation("Vranov-Ortáše"));
        stations.add(new TrainStation("Vranovské Dlhé"));
        stations.add(new TrainStation("Vrbovce"));
        stations.add(new TrainStation("Vrbovce zastávka"));
        stations.add(new TrainStation("Vrbové"));
        stations.add(new TrainStation("Vrútky"));
        stations.add(new TrainStation("Výčapy-Opatovce"));
        stations.add(new TrainStation("Vydrník"));
        stations.add(new TrainStation("Východná"));
        stations.add(new TrainStation("Vysoká nad Kysucou"));
        stations.add(new TrainStation("Vysoká pri Morave"));
        stations.add(new TrainStation("Vysoká pri Morave zastávka"));
        stations.add(new TrainStation("Vyškovce nad Ipľom"));
        stations.add(new TrainStation("Vyšná Myšľa"));
        stations.add(new TrainStation("Vyšné Čabiny"));
        stations.add(new TrainStation("Vyšné Hágy"));
        stations.add(new TrainStation("Záhorská Ves"));
        stations.add(new TrainStation("Zalaba"));
        stations.add(new TrainStation("Zarečie"));
        stations.add(new TrainStation("Závadka nad Hronom obec"));
        stations.add(new TrainStation("Závadka nad Hronom zastávka"));
        stations.add(new TrainStation("Závod"));
        stations.add(new TrainStation("Zbehy"));
        stations.add(new TrainStation("Zbehy obec"));
        stations.add(new TrainStation("Zbojská"));
        stations.add(new TrainStation("Zbudské Dlhé"));
        stations.add(new TrainStation("Zbyňov"));
        stations.add(new TrainStation("Zelené"));
        stations.add(new TrainStation("Zemianska Olča"));
        stations.add(new TrainStation("Zemianske Kostoľany"));
        stations.add(new TrainStation("Zlaté Moravce"));
        stations.add(new TrainStation("Zlaté Moravce závody"));
        stations.add(new TrainStation("Zlaté Moravce-Prílepy"));
        stations.add(new TrainStation("Zlatná na Ostrove"));
        stations.add(new TrainStation("Zlatno"));
        stations.add(new TrainStation("Zlatovce"));
        stations.add(new TrainStation("Zohor"));
        stations.add(new TrainStation("Zvolen mesto"));
        stations.add(new TrainStation("Zvolen nákladná stanica"));
        stations.add(new TrainStation("Zvolen osobná stanica"));
        stations.add(new TrainStation("Zvolen-Bučina"));
        stations.add(new TrainStation("Zvolenská Slatina"));
        stations.add(new TrainStation("Zwardoň PKP"));
        stations.add(new TrainStation("Žabokreky nad Nitrou"));
        stations.add(new TrainStation("Žakarovce"));
        stations.add(new TrainStation("Žarnovica"));
        stations.add(new TrainStation("Želiezovce"));
        stations.add(new TrainStation("Žiar nad Hronom"));
        stations.add(new TrainStation("Žiar nad Hronom zastávka"));
        stations.add(new TrainStation("Žihárec"));
        stations.add(new TrainStation("Žihárec zastávka"));
        stations.add(new TrainStation("Žilina"));
        stations.add(new TrainStation("Žilina Zarečie"));
        stations.add(new TrainStation("Žirany"));
    }

}
